name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    needs: test-frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build Docker images
        run: docker-compose build

      # - name: Push Docker images to GitHub Packages (Optional)
      #   run: |
      #     echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      #     docker-compose push

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" > devops01.pem
          chmod 600 devops01.pem

      - name: Deploy to AWS EC2
        run: |
          ssh -i devops01.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/devops-01  # Change to your project directory on the EC2 instance
            sudo docker-compose down
            git pull origin main
            sudo docker-compose up -d --build
          EOF

      - name: Clean Up SSH Key
        run: rm -f devops01.pem
